name: lost_and_found
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  firebase_core: ^2.1.1
  firebase_analytics: ^10.0.4
  cloud_firestore: ^4.0.4
  firebase_messaging: ^14.0.4
  firebase_auth: ^4.1.1
  firebase_storage: ^11.0.6
  google_maps_flutter: ^2.2.1
  permission_handler: ^10.2.0
  geolocator: ^8.2.0
  geocoding: ^2.0.4
  image_picker: ^0.8.6
  dartz: ^0.10.1
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  build_runner: ^2.1.5
  pull_to_refresh: ^2.0.0
  animate_do: ^3.0.2
  flutter_svg: ^1.1.6
  lit_relative_date_time: ^1.2.0


  
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  hive_generator: ^1.1.1


flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/svgs/
    - assets/fonts/


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf