// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzQror6Hm-S3OLKiW8qkSyp9YkJXFu6rI',
    appId: '1:523283799661:web:ffaa0f79219aa27492a964',
    messagingSenderId: '523283799661',
    projectId: 'lostandfound-a74ef',
    authDomain: 'lostandfound-a74ef.firebaseapp.com',
    storageBucket: 'lostandfound-a74ef.appspot.com',
    measurementId: 'G-W6Q2YMSQ0G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVYWxxHETveDlvretXHvd-MXQdti7gft4',
    appId: '1:523283799661:android:d9f3f04dc9fc3dab92a964',
    messagingSenderId: '523283799661',
    projectId: 'lostandfound-a74ef',
    storageBucket: 'lostandfound-a74ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD292x0tg9cfc04lsOn66N5Z9sVJlWk8gU',
    appId: '1:523283799661:ios:b10d09d56997bc8192a964',
    messagingSenderId: '523283799661',
    projectId: 'lostandfound-a74ef',
    storageBucket: 'lostandfound-a74ef.appspot.com',
    iosClientId: '523283799661-va92io78vh4ltbtlrtpo8ojq34j3hbji.apps.googleusercontent.com',
    iosBundleId: 'com.example.lostAndFound',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD292x0tg9cfc04lsOn66N5Z9sVJlWk8gU',
    appId: '1:523283799661:ios:b10d09d56997bc8192a964',
    messagingSenderId: '523283799661',
    projectId: 'lostandfound-a74ef',
    storageBucket: 'lostandfound-a74ef.appspot.com',
    iosClientId: '523283799661-va92io78vh4ltbtlrtpo8ojq34j3hbji.apps.googleusercontent.com',
    iosBundleId: 'com.example.lostAndFound',
  );
}
